// <auto-generated />
using System;
using BitirmeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeAPI.Migrations
{
    [DbContext(typeof(BitirmeAPIContext))]
    [Migration("20221215122316_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BitirmeAPI.Model.Comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentID"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("commentID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Lesson", b =>
                {
                    b.Property<int>("lessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonID"), 1L, 1);

                    b.Property<string>("lessonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lessonID");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Note", b =>
                {
                    b.Property<int>("noteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("noteID"), 1L, 1);

                    b.Property<int>("notes")
                        .HasColumnType("int");

                    b.HasKey("noteID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Parent", b =>
                {
                    b.Property<int>("parentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("parentID"), 1L, 1);

                    b.Property<string>("parentMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("parentID");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Student", b =>
                {
                    b.Property<int>("studentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentID"), 1L, 1);

                    b.Property<string>("classCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("BitirmeAPI.Model.Teache", b =>
                {
                    b.Property<int>("teacheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacheID"), 1L, 1);

                    b.Property<string>("teacheMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacheName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teachePassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacheSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teacheID");

                    b.ToTable("Teache");
                });
#pragma warning restore 612, 618
        }
    }
}
